---
- name: Deploy workload(s) role on bastion of the shared cluster
  hosts: localhost
  connection: local
  gather_facts: false
  tags:
    - step005
  tasks:

    - name: print out user.info
      debug:
        msg: "{{ item }}"
      loop:
        - "user.info: You can access your bastion via SSH:"
        - "user.info: ssh {{ student_name }}@{{ hostvars[groups['bastions'][0]]['inventory_hostname'] }}.{{ guid }}.{{ osp_cluster_dns_zone }}"
        - "user.info: "
        - "user.info: Make sure you use the username '{{ student_name }}' and the password '{{ hostvars[groups['bastions'][0]]['student_password'] }}' when prompted."
        - "user.info: "
        - "user.info: Your base domain is '{{ osp_cluster_dns_zone }}'"
        - "user.info: "
        - "user.info: For reference, the floating IPs you will use for OpenShift are:"
        - "user.info: "
        - "user.info: API IP: {{ rhv_api_fip|default('undefined') }}"
        - "user.info: API FQDN: api.{{ guid }}.{{ osp_cluster_dns_zone }}"
        - "user.info: "
        - "user.info: Ingress IP: {{ rhv_ingress_fip|default('undefined') }}"
        - "user.info: Ingress FQDN: *.apps.{{ guid }}.{{ osp_cluster_dns_zone }}"
    - debug:
        msg: "Post-Software checks completed successfully"
